### ISSUE TITLE
Issue on IOS since upgrade of flutter to 1.20.1 on stable channel

### ISSUE THREAD

**Issue by Bobby9292** [line/flutter_line_sdk#35]
Hi, 

I recently upgraded flutter to the latest version : 
```
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (4 days ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0
```
And now the build on IOS is failing, I use Android Studio and tried to build for Iphone 11 pro max simulator and a physical Iphone 6.  It works perfectly fine on Android but when trying to build for IOS the following error appears in the console: 

```
/Users/***/.pub-cache/hosted/pub.dartlang.org/flutter_line_sdk-1.3.0/ios/Classes/SwiftFlutterLineSdkPlugin.swift:4:8: error: no such module 'LineSDK'
import LineSDK
Command CompileSwift failed with a nonzero exit code
```
Could you please advice ? 

Please let me know if you need more information. 

Thank you

**Comment by Bobby9292** [comment]
So, when I upgraded Flutter, the compiler told me that the Podfile version was outdated and needed to be deleted in order to be regenerated after build. 

I regenerated the Podfile and didn't notice that the` platform :ios, '8.0'` was commented by default. 
I uncommented and changed to  `platform :ios, '10.0'` and it worked again. 

I don't know if this is just a workaround or a real fix to this issue so please let me know if there is anything else that can be done or if I can close this issue.

Thank you.

**Comment by onevcat** [comment]
Hi,

LINE SDK starts supporting iOS 10.0, so your change is totally good.

You can read more about in in the [set up section](https://github.com/line/flutter_line_sdk#set-up-line-sdk) in the README file.
